package com.replysense.app.domain.intelligence.openai

/**
 * Non-authoritative suggestion generated by OpenAI.
 * Clearly labeled and never merged into core results.
 */
data class EnhancerSuggestion(
    val label: String,
    val content: String,
    val disclaimer: String =
        "Optional phrasing suggestion. Deterministic analysis remains authoritative."
)
